Baumi
IG-2000
Archaic Weapons
 8 
Blaster
 8 
Blaster Artillery
 6 
Bowcaster
 6 
Bows
 6 
Brawling Parry
 6 
Dodge
 7 
Firearms
 10 
Grenade
 7 
Lightsaber
 0 
Melee Combat
 6 
Melee Parry
 6 
Missile Weapons
 6 
Pick Pocket
 6 
Running
 6 
Thrown Weapons
 6 
Vehicle Blasters
 6 
Alien Species
 1 
Bureaucracy
 1 
Business
 1 
Cultures
 1 
Intimidation
 1 
Languages
 1 
Law Enforcement
 1 
Planetary Systems
 1 
Streetwise
 1 
Survival
 1 
Value
 1 
Willpower
 1 
Archaic Starship Piloting
 3 
Astrogation
 5 
Beast Riding
 3 
Capital Ship Gunnery
 3 
Capital Ship Piloting
 3 
Capital Ship Shields
 3 
Communications
 3 
Ground Vehicle Operation
 3 
Hover Vehicle Operation
 3 
Powersuit Operation
 3 
Repulsorlift Operation
 3 
Sensors
 3 
Space Transports
 3 
Starfighter Piloting
 3 
Starship Gunnery
 3 
Starship Shields
 3 
Swoop Operation
 3 
Walker Operation
 3 
Bargain
 2 
Command
 2 
Con
 2 
Forgery
 2 
Gambling
 2 
Hide
 2 
Investigation
 2 
Persuasion
 2 
Search
 2 
Sneak
 2 
Brawling
 4 
Climbing/Jumping
 4 
Lifting
 4 
Stamina
 4 
Swimming
 4 
Armor Repair
 3 
Blaster Repair
 8 
Capital Starship Repair
 2 
Capital Starship Weapon Repair
 2 
Computers
 2 
Demolition
 2 
Droid Programming
 2 
Droid Repair
 2 
First Aid
 3 
Ground Vehicle Repair
 2 
Hover Vehicle Repair
 2 
Medicine
 2 
Repulsorlift Repair
 2 
Security
 2 
Space Transports Repair
 2 
Starfighter Repair
 2 
Starship Weapon Repair
 2 
Walker Repair
 2 
Dexterity
 6 
Knowledge
 1 
Mechanical
 3 
Perception
 2 
Strength
 4 
Technical
 2 
ordmap.sw
 51623 
SC-75 Rifle
 8            -2             0            -8             3             9             0 
Ord Mantell
Map of Ord Mantell
Frag Grenade
Treaty with Boba Fett
modified Blaster Rifle
modified Blaster Rifle
modified Blaster Rifle
modified Blaster Rifle
modified Blaster Rifle

Life-form Scanner
ordmap.sw
Blast armor
 2             0            -1            -6             1124          427          -1             0            -2 
Okay

Okay
 5             8 
 0             0            -1            -4             0 
-1             0             0             0             0 
 0             0             0             0             0 
 0             0             0             0             0 
 0             0             0             0             0 
Room-key
Droid-Manual
Droid parts
Macrobinoculars

modified Blaster Rifle
Bantha horn
Thermal Detonator
Glowrod
Vibro Axe
modified Hold-out Blaster
Cyborg head
Breathing mask
Hydro-Screwdriver
Cyborg-controller
Bantha Steak
Droid parts
Droid parts
Droid parts










Engineering Kit
