Thalok

Archaic Weapons
 3 
Blaster
 9 
Blaster Artillery
 3 
Bowcaster
 3 
Bows
 3 
Brawling Parry
 3 
Dodge
 4 
Firearms
 3 
Grenade
 5 
Lightsaber
 0 
Melee Combat
 3 
Melee Parry
 3 
Missile Weapons
 3 
Pick Pocket
 3 
Running
 3 
Thrown Weapons
 3 
Vehicle Blasters
 3 
Alien Species
 3 
Bureaucracy
 3 
Business
 3 
Cultures
 3 
Intimidation
 3 
Languages
 3 
Law Enforcement
 3 
Planetary Systems
 3 
Streetwise
 3 
Survival
 3 
Value
 3 
Willpower
 3 
Archaic Starship Piloting
 3 
Astrogation
 3 
Beast Riding
 3 
Capital Ship Gunnery
 3 
Capital Ship Piloting
 3 
Capital Ship Shields
 3 
Communications
 3 
Ground Vehicle Operation
 3 
Hover Vehicle Operation
 3 
Powersuit Operation
 3 
Repulsorlift Operation
 3 
Sensors
 3 
Space Transports
 3 
Starfighter Piloting
 3 
Starship Gunnery
 3 
Starship Shields
 3 
Swoop Operation
 3 
Walker Operation
 3 
Bargain
 3 
Command
 3 
Con
 3 
Forgery
 3 
Gambling
 3 
Hide
 3 
Investigation
 3 
Persuasion
 3 
Search
 3 
Sneak
 3 
Brawling
 3 
Climbing/Jumping
 3 
Lifting
 3 
Stamina
 3 
Swimming
 3 
Armor Repair
 3 
Blaster Repair
 3 
Capital Starship Repair
 3 
Capital Starship Weapon Repair
 3 
Computers
 3 
Demolition
 3 
Droid Programming
 3 
Droid Repair
 3 
First Aid
 3 
Ground Vehicle Repair
 3 
Hover Vehicle Repair
 3 
Medicine
 1 
Repulsorlift Repair
 3 
Security
 3 
Space Transports Repair
 3 
Starfighter Repair
 6 
Starship Weapon Repair
 3 
Walker Repair
 3 
Dexterity
 3 
Knowledge
 3 
Mechanical
 3 
Perception
 3 
Strength
 3 
Technical
 3 
me.bas
 61050 
Blaster Rifle
 6            -1             0             0             28            11            0 
Tattooine
Frag Grenade
Frag Grenade
Medpac
Detonite-Pack


Heavy Blaster
Heavy Blaster
Heavy Blaster
Heavy Blaster
me.bas
Blast vest
 1             0            -1            -6             455           96            0             0             0 
Okay

Okay
 5             8 
 0             0             0             0             0 
 0             0             0             0             0 
 0             0             0             0             0 
 0             0             0             0             0 
 0             0             0             0             0 
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator

























