Uncle Sam
Deathwing
Archaic Weapons
 6 
Blaster
 13 
Blaster Artillery
 4 
Bowcaster
 4 
Bows
 4 
Brawling Parry
 4 
Dodge
 6 
Firearms
 4 
Grenade
 9 
Lightsaber
 13 
Melee Combat
 4 
Melee Parry
 4 
Missile Weapons
 4 
Pick Pocket
 4 
Running
 4 
Thrown Weapons
 4 
Vehicle Blasters
 4 
Alien Species
 2 
Bureaucracy
 2 
Business
 2 
Cultures
 2 
Intimidation
 2 
Languages
 2 
Law Enforcement
 2 
Planetary Systems
 2 
Streetwise
 2 
Survival
 2 
Value
 2 
Willpower
 2 
Archaic Starship Piloting
 4 
Astrogation
 5 
Beast Riding
 4 
Capital Ship Gunnery
 10 
Capital Ship Piloting
 5 
Capital Ship Shields
 7 
Communications
 4 
Ground Vehicle Operation
 4 
Hover Vehicle Operation
 4 
Powersuit Operation
 4 
Repulsorlift Operation
 4 
Sensors
 4 
Space Transports
 11 
Starfighter Piloting
 4 
Starship Gunnery
 11 
Starship Shields
 17 
Swoop Operation
 4 
Walker Operation
 4 
Bargain
 3 
Command
 3 
Con
 3 
Forgery
 3 
Gambling
 5 
Hide
 3 
Investigation
 3 
Persuasion
 3 
Search
 3 
Sneak
 3 
Brawling
 5 
Climbing/Jumping
 4 
Lifting
 4 
Stamina
 4 
Swimming
 4 
Armor Repair
 4 
Blaster Repair
 5 
Capital Starship Repair
 2 
Capital Starship Weapon Repair
 2 
Computers
 2 
Demolition
 2 
Droid Programming
 4 
Droid Repair
 7 
First Aid
 3 
Ground Vehicle Repair
 2 
Hover Vehicle Repair
 2 
Medicine
 2 
Repulsorlift Repair
 2 
Security
 2 
Space Transports Repair
 4 
Starfighter Repair
 2 
Starship Weapon Repair
 2 
Walker Repair
 2 
Dexterity
 4 
Knowledge
 2 
Mechanical
 4 
Perception
 3 
Strength
 4 
Technical
 2 
iv.sw
 48768 
Lightsaber
 10           -2             0            -10            33            10            33 
Coruscant


Frag Grenade
Thermal Detonator






iv.sw
Battle suit
 4             0            -1            -6             1281          823          -2             0            -2 
Okay

Okay
 9             8 
 0             0            -1            -4            -2 
-1            -1            -3            -2            -2 
-1            -3            -1            -6             0 
 0             0             0             0             0 
 0             0             0             0             0 
head
modified Blaster Rifle
Ship parts
Deathwing-License
Hydro-Screwdriver
Engineering Kit
Ship parts
Droid parts
Armor parts
Narcotics for Mos Eisley














DROP-SHUTTLE





