Thalok
Epoch
Archaic Weapons
 10 
Blaster
 11 
Blaster Artillery
 10 
Bowcaster
 7 
Bows
 4 
Brawling Parry
 4 
Dodge
 12 
Firearms
 4 
Grenade
 12 
Lightsaber
 12 
Melee Combat
 4 
Melee Parry
 4 
Missile Weapons
 4 
Pick Pocket
 4 
Running
 4 
Thrown Weapons
 4 
Vehicle Blasters
 11 
Alien Species
 3 
Bureaucracy
 3 
Business
 3 
Cultures
 3 
Intimidation
 3 
Languages
 3 
Law Enforcement
 10 
Planetary Systems
 10 
Streetwise
 3 
Survival
 8 
Value
 3 
Willpower
 3 
Archaic Starship Piloting
 9 
Astrogation
 11 
Beast Riding
 11 
Capital Ship Gunnery
 11 
Capital Ship Piloting
 11 
Capital Ship Shields
 11 
Communications
 4 
Ground Vehicle Operation
 11 
Hover Vehicle Operation
 11 
Powersuit Operation
 4 
Repulsorlift Operation
 11 
Sensors
 11 
Space Transports
 4 
Starfighter Piloting
 11 
Starship Gunnery
 11 
Starship Shields
 11 
Swoop Operation
 4 
Walker Operation
 11 
Bargain
 3 
Command
 3 
Con
 3 
Forgery
 3 
Gambling
 4 
Hide
 10 
Investigation
 10 
Persuasion
 3 
Search
 3 
Sneak
 10 
Brawling
 1 
Climbing/Jumping
 8 
Lifting
 1 
Stamina
 1 
Swimming
 1 
Armor Repair
 3 
Blaster Repair
 3 
Capital Starship Repair
 10 
Capital Starship Weapon Repair
 10 
Computers
 10 
Demolition
 10 
Droid Programming
 10 
Droid Repair
 10 
First Aid
 10 
Ground Vehicle Repair
 10 
Hover Vehicle Repair
 10 
Medicine
 5 
Repulsorlift Repair
 10 
Security
 3 
Space Transports Repair
 10 
Starfighter Repair
 10 
Starship Weapon Repair
 10 
Walker Repair
 10 
Dexterity
 4 
Knowledge
 3 
Mechanical
 4 
Perception
 3 
Strength
 4 
Technical
 3 
space.bas
 99175 
Lightsaber
 15           -2             0            -10            40            9             0 
Kosma
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
Breathing mask
Blast vest
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
space.bas
damaged Battle suit
 3            -1            -1            -6             1344          450          -2             0            -1 
Okay
zufall
Okay
 6             8 
-3            -1            -1            -4            -5 
-1             6            -1             0             0 
 0            -2             0             0            -1 
 0             0             0             0             0 
 0             0             0             0             0 
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
Thermal Detonator
Detonite-Pack
Holo-movie (XXX-rated)




Detonite -Pack
Detonite -Pack
Cyborg head
Cyborg head

Security Pass
Glowrod
Lobot -controller
Droid parts
Droid parts







